# Generated by Django 4.1.4 on 2022-12-25 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAR_COMPANY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CAR_TYPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartypename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CAR_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('fuel_efficiency', models.CharField(max_length=255)),
                ('fuel_tank_capacity', models.CharField(max_length=255)),
                ('front_suspension', models.CharField(max_length=255)),
                ('rear_suspension', models.CharField(max_length=255)),
                ('tyre_size', models.CharField(max_length=255)),
                ('front_brake', models.CharField(max_length=255)),
                ('rear_brake', models.CharField(max_length=255)),
                ('ground_clearance', models.CharField(max_length=255)),
                ('seating_capacity', models.CharField(max_length=255)),
                ('boot_capacity', models.CharField(max_length=255)),
                ('max_torque', models.CharField(max_length=255)),
                ('trasmission', models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default=None, max_length=255, null=True)),
                ('cylinders', models.CharField(max_length=255)),
                ('engine_cc', models.CharField(max_length=255)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='image/media/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='image/media/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='image/media/')),
                ('fuel_type', models.CharField(blank=True, choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELETRIC', 'Eletric')], default=None, max_length=255, null=True)),
                ('car_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car_company')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car_type')),
            ],
        ),
    ]
