# Generated by Django 4.1.4 on 2022-12-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TYPE',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Catogoty Name')),
            ],
            options={
                'db_table': 'CAR TYPE',
            },
        ),
        migrations.RemoveField(
            model_name='car_details',
            name='car_company',
        ),
        migrations.RemoveField(
            model_name='car_details',
            name='car_type',
        ),
        migrations.DeleteModel(
            name='CAR_COMPANY',
        ),
        migrations.DeleteModel(
            name='CAR_DETAILS',
        ),
        migrations.DeleteModel(
            name='CAR_TYPE',
        ),
    ]
