# Generated by Django 4.1.4 on 2022-12-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_type_remove_car_details_car_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMPANY',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Catogoty Name')),
            ],
            options={
                'db_table': 'CAR COMPANY',
            },
        ),
    ]
