# Generated by Django 4.1.4 on 2022-12-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='DETAILS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=255, verbose_name='Car Name')),
                ('stock', models.IntegerField(verbose_name='Stock Avaliable')),
                ('price', models.IntegerField(verbose_name='Price Of Car')),
                ('fuel_efficiency', models.CharField(max_length=255, verbose_name='Mileage In Kilometers')),
                ('fuel_tank_capacity', models.CharField(max_length=255, verbose_name='Fuel Tank Capacity In Liter')),
                ('front_suspension', models.CharField(max_length=255, verbose_name='Suspension Type Front')),
                ('rear_suspension', models.CharField(max_length=255, verbose_name='Suspension Type Rear')),
                ('tyre_size', models.IntegerField(verbose_name='Tyre Size')),
                ('front_brake', models.CharField(max_length=255, verbose_name='Front Brake Type')),
                ('rear_brake', models.CharField(max_length=255, verbose_name='Rear Brake Type')),
                ('ground_clearance', models.CharField(max_length=255, verbose_name='Ground Clearance')),
                ('seating_capacity', models.IntegerField(verbose_name='Total Seat')),
                ('boot_capacity', models.IntegerField(verbose_name='Capacity Of Boot Space In Liter')),
                ('max_torque', models.IntegerField(verbose_name='Max Torque')),
                ('trasmission', models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default=None, max_length=255, null=True, verbose_name='Type Of Trasmission')),
                ('cylinders', models.IntegerField(verbose_name='Max Number Of Cylinders')),
                ('engine_cc', models.IntegerField(verbose_name='Engine CC Of Car')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='image/media/', verbose_name='Exterior Image Of Car')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='image/media/', verbose_name='Interior Image Of Car')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='image/media/', verbose_name='Total Look')),
                ('fuel_type', models.CharField(blank=True, choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELETRIC', 'Eletric')], default=None, max_length=255, null=True, verbose_name='What Type Of Energy Using (Fuel TYPE)')),
                ('car_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.company', verbose_name='Car Company')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.type', verbose_name='Car Type')),
            ],
            options={
                'db_table': 'CAR DETAILS',
            },
        ),
    ]
