# Generated by Django 4.1.4 on 2022-12-27 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0004_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='ground_clearance',
            field=models.CharField(max_length=255, verbose_name='Ground Clearance In mm'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='House Address Of Customer')),
                ('LicenceIDNumber', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Licence ID Number Of Customer')),
                ('Pincode', models.IntegerField(verbose_name='Pincode Of Customer')),
                ('ContactNumber', models.IntegerField(verbose_name='Contact Number Of Customer')),
                ('application_code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Application Id Of Order')),
                ('State', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='State')),
                ('City', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='City')),
                ('Date_of_booking', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Booking')),
                ('carnameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.details', verbose_name='Car Name')),
                ('customerid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'db_table': 'CUSTOMER ORDER DETAILS',
            },
        ),
    ]
