# Generated by Django 4.1.4 on 2022-12-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_details_ground_clearance_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ContactNumber',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Contact Number Of Customer'),
        ),
    ]
