# Generated by Django 4.1.4 on 2022-12-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1200, null=True, verbose_name='Description Of The Vehicle'),
        ),
        migrations.AlterField(
            model_name='information',
            name='general_information',
            field=models.CharField(blank=True, default=None, max_length=1200, null=True, verbose_name='General Information Of The Vehicle'),
        ),
        migrations.AlterField(
            model_name='information',
            name='vehicle_overview',
            field=models.CharField(blank=True, default=None, max_length=1200, null=True, verbose_name='Vehicle overview'),
        ),
    ]
