# Generated by Django 4.1.4 on 2022-12-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_information_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
