# Generated by Django 4.1.4 on 2023-01-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='hi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'hi my name',
                'verbose_name_plural': 'hi my name',
            },
        ),
    ]
