# Generated by Django 4.1.4 on 2023-01-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_hi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hi',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Car Company', 'verbose_name_plural': 'Car Company'},
        ),
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name': 'Details', 'verbose_name_plural': 'Details'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Information', 'verbose_name_plural': 'Information'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Car Type', 'verbose_name_plural': 'Car Type'},
        ),
    ]
