# Generated by Django 4.1.4 on 2023-01-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_delete_hi_alter_company_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAccessories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/media/', verbose_name='Product Image')),
                ('price', models.IntegerField(verbose_name='Price Of Product')),
                ('Product', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Additional Accessories',
                'verbose_name_plural': 'Additional Accessories',
                'db_table': 'Additional Accessories',
            },
        ),
    ]
