# Generated by Django 4.1.4 on 2023-01-06 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_remove_information_booking_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Add Car Company And', 'verbose_name_plural': 'Car Company'},
        ),
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name': 'Vechile Information', 'verbose_name_plural': 'Vechile Information'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Vechile Description', 'verbose_name_plural': 'Vechile Description'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Customer Orders', 'verbose_name_plural': 'Customer Booking'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Add Car Type And', 'verbose_name_plural': 'Car Type'},
        ),
        migrations.CreateModel(
            name='Tax_and_other',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Road_tax', models.IntegerField(verbose_name='Road tax Amount')),
                ('Insurance', models.IntegerField(verbose_name='Insurance Amount')),
                ('Reg_amt', models.IntegerField(verbose_name='Registration Amount')),
                ('delivery_days', models.IntegerField(verbose_name='Delivery Days Of Car')),
                ('delivery_cost', models.IntegerField(verbose_name='Delivery Cost Of The car')),
                ('booking_amount', models.IntegerField(verbose_name='Booking Amount')),
                ('carnameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.details', verbose_name='Car Name')),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.company', verbose_name='Car Company')),
                ('typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.type', verbose_name='Car Type')),
            ],
            options={
                'verbose_name': 'Add Tax And Other Detalis',
                'verbose_name_plural': 'Tax And Other Info',
                'db_table': 'TAX AND OTHER',
            },
        ),
    ]
