# Generated by Django 4.1.4 on 2023-01-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_company_options_alter_details_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tax_and_other',
            new_name='Taxandother',
        ),
    ]
