# Generated by Django 4.1.4 on 2023-01-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_details_options_order_accessorieslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Description Of The Vehicle'),
        ),
        migrations.AlterField(
            model_name='information',
            name='general_information',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='General Information Of The Vehicle'),
        ),
        migrations.AlterField(
            model_name='information',
            name='vehicle_overview',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Vehicle overview'),
        ),
    ]
