# Generated by Django 4.1.4 on 2023-01-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_order_tax_order_total_alter_order_accessorieslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxandother',
            name='Insurance',
            field=models.FloatField(verbose_name='Insurance Amount'),
        ),
        migrations.AlterField(
            model_name='taxandother',
            name='Reg_amt',
            field=models.FloatField(verbose_name='Registration Amount'),
        ),
        migrations.AlterField(
            model_name='taxandother',
            name='Road_tax',
            field=models.FloatField(verbose_name='Road tax Amount'),
        ),
    ]
