# Generated by Django 4.1.4 on 2023-01-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_insurance_taxandother_insu_nameid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxandother',
            name='insu_nameid',
        ),
    ]
