# Generated by Django 4.1.4 on 2023-02-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance_amount',
            field=models.FloatField(default=None, null=True, verbose_name='Balance Amount After Advance'),
        ),
    ]
