# Generated by Django 4.1.4 on 2023-02-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_alter_order_accssamt_alter_order_insuramt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.FloatField(default=0.0, null=True, verbose_name='Car Rating'),
        ),
    ]
