# Generated by Django 4.1.4 on 2023-02-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_order_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Car Count'),
        ),
    ]
