# Generated by Django 4.1.4 on 2023-02-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0032_order_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rating_count',
        ),
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.IntegerField(default=0, null=True, verbose_name='Car Rating'),
        ),
    ]
