# Generated by Django 4.1.4 on 2023-02-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_remove_order_rating_count_alter_order_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='average_rating',
            field=models.FloatField(default=0.0, null=True, verbose_name='Average Rating Of Car'),
        ),
        migrations.AddField(
            model_name='order',
            name='average_rating',
            field=models.FloatField(default=0.0, null=True, verbose_name='Average Rating Of Car'),
        ),
    ]
