# Generated by Django 4.1.4 on 2023-02-22 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0034_details_average_rating_order_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='House Address Of Customer')),
                ('LicenceIDNumber', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Licence ID Number Of Customer')),
                ('Pincode', models.IntegerField(verbose_name='Pincode Of Customer')),
                ('ContactNumber', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Contact Number Of Customer')),
                ('application_code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Application Id Of Order')),
                ('State', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='State')),
                ('City', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='City')),
                ('Date_of_booking', models.DateTimeField(auto_now_add=True, verbose_name='Date Of Booking')),
                ('carnameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.details', verbose_name='Car Name')),
                ('customerid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Test Drive Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'TEST DRIVE',
            },
        ),
    ]
