# Generated by Django 4.1.4 on 2023-02-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0035_testdrive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdrive',
            options={'verbose_name': 'Test Drive Booking', 'verbose_name_plural': 'Test Drive Bookings'},
        ),
        migrations.AddField(
            model_name='testdrive',
            name='Test_drive_rating',
            field=models.IntegerField(default=0, null=True, verbose_name='Rating Of The Test Drive'),
        ),
    ]
