# Generated by Django 4.1.4 on 2023-03-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0037_numberplate_testdrive_test_drive_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdrive',
            name='test_drive_date',
        ),
    ]
