# Generated by Django 4.1.4 on 2023-03-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0038_remove_testdrive_test_drive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='dattte',
            field=models.DateTimeField(null=True, verbose_name='Customer Perfer Time For Test Drive'),
        ),
    ]
