# Generated by Django 4.1.4 on 2023-03-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0039_testdrive_dattte'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedVechiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='Car Name')),
                ('company', models.TextField(blank=True, default=None, null=True, verbose_name='Company Name')),
                ('ttype', models.TextField(blank=True, default=None, null=True, verbose_name='Car Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/media/', verbose_name='Car Image')),
            ],
            options={
                'verbose_name': 'Add Featured Vechiles',
                'verbose_name_plural': 'Featured Vechiles',
                'db_table': 'Featured Vechiles',
            },
        ),
    ]
